enyo.depends(
	"types/",
	"PodCatcher.js",
	"PodcastList.js",
	"EpisodeList.js",
	"EpisodeView.js",
	"AddPodcastPopup.js",
	"DownloadManager.js",
	"SuggestPopup.js",
	"LoginPopup.js",
	"Utilities.js"
);
